FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY backend/ ./backend
COPY wait-for-mysql.sh /wait-for-mysql.sh
RUN chmod +x /wait-for-mysql.sh

EXPOSE 3000

CMD ["/wait-for-mysql.sh", "node", "backend/app.js"]

