version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hilmi123
      MYSQL_DATABASE: keamanan_db
      # HAPUS baris MYSQL_USER dan MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-api:
    build:
      context: ./flask-api
      dockerfile: Dockerfile.flask
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: hilmi123
      DB_NAME: keamanan_db

  node-backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: hilmi123
      DB_NAME: keamanan_db

volumes:
  mysql_data:

