FROM node:18

WORKDIR /app

# Install mysql-client
RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY backend/ ./backend

COPY wait-for-mysql.sh /wait-for-mysql.sh
RUN chmod +x /wait-for-mysql.sh

EXPOSE 3000

CMD ["/wait-for-mysql.sh", "node", "backend/app.js"]

