FROM python:3.10-slim

WORKDIR /app

# Tambahkan mysql-client terlebih dahulu
RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY wait-for-mysql.sh /wait-for-mysql.sh
RUN chmod +x /wait-for-mysql.sh

EXPOSE 5000

ENTRYPOINT ["/wait-for-mysql.sh"]
CMD ["python", "app.py"]

